//===============================================================================//
//
// SCRIPT: SCR_BATTLE_QUEUE_MANA_GAIN
// FUNCTION: Queues Mana generated by the currently resolving player Card.
//           Queued Mana is awarded after that Card's Mana cost is paid.
//
// ARGUMENTS: _ct_amount is the amount of Mana to generate.
// RETURNS: Amount successfully queued.
//
//===============================================================================//

function scr_battle_queue_mana_gain(_ct_amount=1){

	//----------------//
	//VALIDATE AMOUNT//
	//----------------//
	_ct_amount = floor(_ct_amount);

	if (_ct_amount <= 0){
		return 0;
	}

	//----------------//
	//VALIDATE CARD//
	//----------------//
	if (!instance_exists(global.ref_cast_card)){
		return 0;
	}

	//----------------//
	//VALIDATE CASTER//
	//----------------//
	if (!instance_exists(global.ref_caster_beast)){
		return 0;
	}

	if (global.ref_caster_beast._str_team != "PLAYER"){
		return 0;
	}

	//================//
	//QUEUE MANA//
	//================//
	if (
		!variable_instance_exists(
			global.ref_cast_card,
			"_ct_pending_mana_gain"
		)
	){
		global.ref_cast_card._ct_pending_mana_gain = 0;
	}

	global.ref_cast_card._ct_pending_mana_gain += _ct_amount;

	return _ct_amount;
}