//===============================================================================//
//
// SCRIPT: SCR_CARD_VERMILION_THE_RED_FEAST
// FUNCTION: Consumes up to 3 Bleed from each Beast on the selected team.
//           Deals 4 MAG damage per Bleed consumed.
//           Heals the caster for 50% of total actual HP damage dealt.
//           Grants the caster Boost for 2 rounds.
//
// ARGUMENTS: _stct_card, _ref_caster, _ref_target.
// RETURNS: No value.
//
//===============================================================================//

function scr_card_vermilion_the_red_feast(_stct_card,_ref_caster,_ref_target){

	#region VALIDATION

	
	if (_ref_caster._val_cur_hp <= 0){
		return;
	}

	//================//
	//VALIDATE TARGET//
	//================//
	if (!instance_exists(_ref_target)){
		return;
	}

	//================//
	//GET TARGET TEAM//
	//================//
	var _list_targets = scr_battle_get_target_team_list(_ref_target);

	if (
		_list_targets == undefined ||
		!ds_exists(_list_targets,ds_type_list)
	){
		return;
	}

	#endregion

	#region TARGET SNAPSHOT

	//================//
	//SNAPSHOT TEAM//
	//================//
	var _arr_targets = [];

	for (
		var _it_target = 0;
		_it_target < ds_list_size(_list_targets);
		_it_target++
	){

		var _ref_beast = ds_list_find_value(
			_list_targets,
			_it_target
		);

		if (!instance_exists(_ref_beast)){
			continue;
		}

		if (
			_ref_beast._str_list != "ALIVE" ||
			_ref_beast._val_cur_hp <= 0
		){
			continue;
		}

		array_push(_arr_targets,_ref_beast);
	}

	//================//
	//STORE CAST CONTEXT//
	//================//
	var _ref_cast_card = global.ref_cast_card;

	//================//
	//TRACK TOTAL DAMAGE//
	//================//
	var _val_total_hp_damage = 0;

	#endregion

	#region RED FEAST

	//================//
	//PROCESS TEAM//
	//================//
	for (
		var _it_target = 0;
		_it_target < array_length(_arr_targets);
		_it_target++
	){

		var _ref_beast = _arr_targets[_it_target];

		//================//
		//VALIDATE BEAST//
		//================//
		if (!instance_exists(_ref_beast)){
			continue;
		}

		if (
			_ref_beast._str_list != "ALIVE" ||
			_ref_beast._val_cur_hp <= 0
		){
			continue;
		}


		//================//
		//CONSUME BLEED//
		//================//
		var _ct_bleed_consumed = scr_status_consume_bleed(
			_ref_beast,
			3
		);

		//================//
		//NO BLEED//
		//================//
		if (_ct_bleed_consumed <= 0){
			continue;
		}

		//================//
		//CALCULATE DAMAGE//
		//================//
		var _val_damage = (
			_ct_bleed_consumed *
			_stct_card._val_card_magnitude
		);

		//================//
		//BLEED FEEDBACK//
		//================//
		scr_gui_spawn_popup_scrolling(
			"TEXT",
			"-" + string(_ct_bleed_consumed) + " BLEED",
			undefined,
			c_red,
			_ref_beast.x,
			_ref_beast.y - 48
		);

		//========================//
		//SNAPSHOT DAMAGE LOG SIZE//
		//========================//
		var _it_damage_start = 0;

		if (
			instance_exists(_ref_cast_card) &&
			variable_instance_exists(_ref_cast_card,"_arr_damage_results") &&
			is_array(_ref_cast_card._arr_damage_results)
		){

			_it_damage_start = array_length(
				_ref_cast_card._arr_damage_results
			);
		}

		//================//
		//DEAL MAG DAMAGE//
		//================//
		scr_battle_damage_target(
			"LINEAR",
			_ref_caster,
			_ref_beast,
			_val_damage,
			{card: _stct_card, card_instance: global.ref_cast_card}
		);

		//================//
		//VALIDATE CARD//
		//================//
		if (!instance_exists(_ref_cast_card)){
			continue;
		}

		if (
			!variable_instance_exists(_ref_cast_card,"_arr_damage_results") ||
			!is_array(_ref_cast_card._arr_damage_results)
		){
			continue;
		}

		//==========================//
		//COUNT ACTUAL HP DAMAGE//
		//==========================//
		/*
			Read the damage result generated by this specific hit.

			Do not use _val_final_damage, which includes damage
			that may have been absorbed by Armor, Overhealth,
			or Minions.

			Reading the result array also prevents a later
			damage reaction from overwriting the relevant result.
		*/

		for (
			var _it_damage = _it_damage_start;
			_it_damage < array_length(_ref_cast_card._arr_damage_results);
			_it_damage++
		){

			var _stct_result = _ref_cast_card._arr_damage_results[
				_it_damage
			];

			if (!is_struct(_stct_result)){
				continue;
			}

			if (_stct_result._ref_target != _ref_beast){
				continue;
			}

			if (_stct_result._ref_caster != _ref_caster){
				continue;
			}

			if (_stct_result._str_origin != "SCR_BATTLE_DAMAGE_TARGET"){
				continue;
			}

			if (_stct_result._str_mode != "STANDARD"){
				continue;
			}

			_val_total_hp_damage += max(
				0,
				_stct_result._val_hp_damage
			);

			// Only count the primary Red Feast hit.
			break;
		}
	}

	#endregion

	#region HEAL CASTER

	//================//
	//VALIDATE CASTER//
	//================//
	if (
		instance_exists(_ref_caster) &&
		_ref_caster._str_list == "ALIVE" &&
		_ref_caster._val_cur_hp > 0
	){

		//================//
		//CALCULATE HEAL//
		//================//
		var _val_healing = floor(
			_val_total_hp_damage
		);

		//================//
		//RESTORE CASTER HP//
		//================//
		if (_val_healing > 0){

			scr_battle_heal_target(
				"FIXED",
				_val_healing,
				_ref_caster
			);
		}

		//================//
		//SET BUFF TARGET//
		//================//

		//================//
		//GRANT BOOST//
		//================//
		scr_status_apply_buff("BOOST", _ref_caster, 25, 2);
	}

	#endregion

	#region CLEANUP


	#endregion
}